<input name="page" id="page" type="hidden" />
<input name="limit" id="limit" type="hidden" />
<input name="total_count" id="total_count" value="0" type="hidden" />
<input name="request" id="request" type="hidden" value="1" />
<div class="success-message" style="display:none;"></div>
<div class="message message-success success" style="display:none;">
    <div data-ui-id="messages-message-success">Csv File Created Successfully.</div>
</div>

    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="button" id="ajax-customers-id" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?= __('Import Customers') ?></span>
            </button>
            <button type="button" id="ajax-product-id" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?= __('Import Product') ?></span>
            </button>
        </div>
    </div>

 <script>
    require(['jquery', 'jquery/ui'], function($) {

        jQuery('#ajax-customers-id').click(function() {
            customers();
        });

        jQuery('#ajax-product-id').click(function() {
            products();
        });

        jQuery('#ajax-salesorders-id').click(function() {
            salesorders();
        });

        function customers() {
            var ajaxRequest;
            ajaxRequest = jQuery.ajax({
                url: "<?php echo $this->getAjaxCustomersUrl(); ?>",
                data: {
                    form_key: window.FORM_KEY
                },
                type: 'POST',
                dataType: 'json',
                success: function(transport) {
                    var response = JSON.parse(transport.responseText);
                    console.log(transport);
                }
            });
        }

        function products() {
            var ajaxRequest;
            ajaxRequest = jQuery.ajax({
                url: "<?php echo $this->getAjaxProductsUrl(); ?>",
                data: {
                    form_key: window.FORM_KEY
                },
                type: 'POST',
                dataType: 'json',
                success: function(transport) {
                    // var response = JSON.parse(transport.responseText);
                    $(".message-success").css("display", "Block");
                }
            });
        }

        function salesorders() {
            var ajaxRequest;
            ajaxRequest = jQuery.ajax({
                url: "<?php echo $this->getAjaxSalesOrdersUrl(); ?>",
                data: {
                    form_key: window.FORM_KEY
                },
                type: 'POST',
                dataType: 'json',
                success: function(transport) {
                    var response = JSON.parse(transport.responseText);
                    console.log(transport);
                }
            });
        }
    });
</script>